#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------------------------------------------------------------
   Flag parsing: JS-style flags -> PCRE2 options
   ------------------------------------------------------------ */

static uint32_t parse_flags(const char* flags)
{
  uint32_t opts = 0;
  for (const char* f = flags; *f; ++f) {
    switch (*f) {
    case 'i':
      opts |= PCRE2_CASELESS;
      break;
    case 'm':
      opts |= PCRE2_MULTILINE;
      break;
    case 's':
      opts |= PCRE2_DOTALL;
      break;
    case 'u':
      opts |= PCRE2_UTF;
      break;
    case 'g': /* handled by caller, not PCRE */
      break;
    default:
      printf("error: unknown regex flag '%c'\n", *f);
      exit(2);
    }
  }
  return opts;
}

/* ------------------------------------------------------------
   Emit serialized bytes as a C file
   ------------------------------------------------------------ */

static int write_c_file(const char* path,
                        const char* symbol,
                        const char* pattern,
                        const char* flags,
                        const uint8_t* bytes,
                        size_t size)
{
  FILE* f = fopen(path, "w");
  if (!f) {
    printf("error: failed to open output file: %s\n", path);
    return 0;
  }

  fprintf(f,
          "// ------------------------------------------------------------------\n"
          "// Generated by haze-regex-compile\n"
          "// Pattern: %s\n"
          "// Flags:   %s\n"
          "// ------------------------------------------------------------------\n\n"
          "#include <stdint.h>\n"
          "#include <stddef.h>\n\n",
          pattern,
          flags);

  fprintf(f, "const uint8_t %s_data[] = {\n", symbol);

  for (size_t i = 0; i < size; ++i) {
    if (i % 12 == 0) {
      fprintf(f, "    ");
    }
    fprintf(f, "0x%02X,", bytes[i]);
    if (i % 12 == 11 || i + 1 == size) {
      fprintf(f, "\n");
    }
  }

  fprintf(f,
          "};\n\n"
          "const size_t %s_size = sizeof(%s_data);\n",
          symbol,
          symbol);

  fclose(f);
  return 1;
}

/* ------------------------------------------------------------
   Main
   ------------------------------------------------------------ */

int main(int argc, char** argv)
{
  if (argc != 5) {
    printf("usage:\n"
           "  %s <output_c_path> <symbol_name> <pattern> <flags>\n",
           argv[0]);
    return 2;
  }

  const char* out_path = argv[1];
  const char* symbol = argv[2];
  const char* pattern = argv[3];
  const char* flags = argv[4];

  uint32_t options = parse_flags(flags);

  /* ------------------------------------------------------------
     Compile regex
     ------------------------------------------------------------ */

  int error_code;
  PCRE2_SIZE error_offset;

  pcre2_code* code
      = pcre2_compile((PCRE2_SPTR)pattern, PCRE2_ZERO_TERMINATED, options, &error_code, &error_offset, NULL);
  const pcre2_code* code_const = code;

  if (!code) {
    PCRE2_UCHAR buffer[256];
    pcre2_get_error_message(error_code, buffer, sizeof(buffer));

    printf("regex compile error at offset %zu: %s\n", (size_t)error_offset, buffer);
    return 1;
  }

  /* ------------------------------------------------------------
     Serialize compiled regex
     ------------------------------------------------------------ */

  PCRE2_UCHAR* serialized = NULL;
  PCRE2_SIZE serialized_size = 0;

  int rc = pcre2_serialize_encode(&code_const, 1, &serialized, &serialized_size, NULL);

  if (rc != 1) {
    printf("error: failed to serialize compiled regex\n");
    pcre2_code_free(code);
    return 1;
  }

  /* ------------------------------------------------------------
     Emit C file
     ------------------------------------------------------------ */

  int ok = write_c_file(out_path, symbol, pattern, flags, (const uint8_t*)serialized, (size_t)serialized_size);

  pcre2_serialize_free(serialized);
  pcre2_code_free(code);

  if (!ok) {
    return 2;
  }

  return 0;
}
