#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#endif

/* ------------------------------------------------------------
   Flag parsing: JS-style flags -> PCRE2 options
   ------------------------------------------------------------ */

/* Returns 0 on success. On failure the offending flag is written to `bad` and
   the call returns non-zero, so server mode can fail one request instead of
   tearing down a process that is serving the whole build. */
static int parse_flags(const char* flags, uint32_t* out, char* bad)
{
  uint32_t opts = 0;
  for (const char* f = flags; *f; ++f) {
    switch (*f) {
    case 'i':
      opts |= PCRE2_CASELESS;
      break;
    case 'm':
      opts |= PCRE2_MULTILINE;
      break;
    case 's':
      opts |= PCRE2_DOTALL;
      break;
    case 'u':
      opts |= PCRE2_UTF;
      break;
    case 'g': /* handled by caller, not PCRE */
      break;
    default:
      *bad = *f;
      return 1;
    }
  }
  *out = opts;
  return 0;
}

/* ------------------------------------------------------------
   Emit serialized bytes as a C file
   ------------------------------------------------------------ */

static const char HEX[] = "0123456789ABCDEF";

/* A growable output buffer. A module's regexes are all formatted into one of
   these and written with a single call: the actual cost here is not the
   formatting (PCRE2 compile is ~0.01ms, serialising ~0.001ms) but the write
   itself, ~2.5ms per file on Windows once the filesystem and virus scanner
   have had their turn. Emitting one file per module instead of one per regex
   is therefore worth roughly 2.5ms times every regex after the first. */
typedef struct {
  char* data;
  size_t len;
  size_t cap;
} outbuf;

static int buf_reserve(outbuf* b, size_t extra)
{
  if (b->len + extra <= b->cap) {
    return 1;
  }
  size_t want = (b->cap ? b->cap : 65536);
  while (want < b->len + extra) {
    want *= 2;
  }
  char* next = (char*)realloc(b->data, want);
  if (!next) {
    return 0;
  }
  b->data = next;
  b->cap = want;
  return 1;
}

/* Append one regex blob as C definitions. */
static int buf_emit_blob(outbuf* b,
                         const char* symbol,
                         const char* pattern,
                         const char* flags,
                         const uint8_t* bytes,
                         size_t size)
{
  const size_t sym_len = strlen(symbol);
  const size_t need = 512 + strlen(pattern) + strlen(flags) + 3 * sym_len + size * 5 + (size / 12 + 2) * 8;
  if (!buf_reserve(b, need)) {
    return 0;
  }

  b->len += (size_t)snprintf(b->data + b->len,
                             b->cap - b->len,
                             "// Pattern: %s\n"
                             "// Flags:   %s\n"
                             "const uint8_t %s_data[] = {\n",
                             pattern,
                             flags,
                             symbol);

  for (size_t i = 0; i < size; ++i) {
    if (i % 12 == 0) {
      b->data[b->len++] = ' ';
      b->data[b->len++] = ' ';
      b->data[b->len++] = ' ';
      b->data[b->len++] = ' ';
    }
    b->data[b->len++] = '0';
    b->data[b->len++] = 'x';
    b->data[b->len++] = HEX[bytes[i] >> 4];
    b->data[b->len++] = HEX[bytes[i] & 0x0F];
    b->data[b->len++] = ',';
    if (i % 12 == 11 || i + 1 == size) {
      b->data[b->len++] = '\n';
    }
  }

  b->len += (size_t)snprintf(b->data + b->len,
                             b->cap - b->len,
                             "};\n\nconst size_t %s_size = sizeof(%s_data);\n\n",
                             symbol,
                             symbol);
  return 1;
}

static int buf_write(const outbuf* b, const char* path)
{
  FILE* f = fopen(path, "wb");
  if (!f) {
    return 0;
  }
  size_t written = fwrite(b->data, 1, b->len, f);
  fclose(f);
  return written == b->len;
}

static void buf_header(outbuf* b)
{
  buf_reserve(b, 512);
  b->len += (size_t)snprintf(b->data + b->len,
                             b->cap - b->len,
                             "// ------------------------------------------------------------------\n"
                             "// Generated by haze-regex-compile\n"
                             "// ------------------------------------------------------------------\n\n"
                             "#include <stdint.h>\n"
                             "#include <stddef.h>\n\n");
}

/* ------------------------------------------------------------
   Compile one regex to a .c file.

   Returns 0 on success; on failure fills `err` with a one-line message.
   Both entry points below go through this, so the two modes cannot drift.
   ------------------------------------------------------------ */

/* Compile one regex and append its C definitions to `b`. */
static int compile_into(outbuf* b,
                        const char* symbol,
                        const char* pattern,
                        const char* flags,
                        char* err,
                        size_t errsz)
{
  uint32_t options = 0;
  char bad = 0;
  if (parse_flags(flags, &options, &bad) != 0) {
    snprintf(err, errsz, "unknown regex flag '%c'", bad);
    return 1;
  }

  int error_code;
  PCRE2_SIZE error_offset;
  pcre2_code* code = pcre2_compile(
      (PCRE2_SPTR)pattern, PCRE2_ZERO_TERMINATED, options, &error_code, &error_offset, NULL);

  if (!code) {
    PCRE2_UCHAR buffer[256];
    pcre2_get_error_message(error_code, buffer, sizeof(buffer));
    snprintf(err, errsz, "regex compile error at offset %zu: %s", (size_t)error_offset, (const char*)buffer);
    return 1;
  }

  const pcre2_code* code_const = code;
  PCRE2_UCHAR* serialized = NULL;
  PCRE2_SIZE serialized_size = 0;
  int rc = pcre2_serialize_encode(&code_const, 1, &serialized, &serialized_size, NULL);

  if (rc != 1) {
    snprintf(err, errsz, "failed to serialize compiled regex");
    pcre2_code_free(code);
    return 1;
  }

  int ok = buf_emit_blob(b, symbol, pattern, flags, (const uint8_t*)serialized, (size_t)serialized_size);

  pcre2_serialize_free(serialized);
  pcre2_code_free(code);

  if (!ok) {
    snprintf(err, errsz, "out of memory");
    return 1;
  }
  return 0;
}

/* One regex, one file. Used by the one-shot CLI and as the fallback path. */
static int compile_one(const char* out_path,
                       const char* symbol,
                       const char* pattern,
                       const char* flags,
                       char* err,
                       size_t errsz)
{
  outbuf b = { NULL, 0, 0 };
  buf_header(&b);
  int rc = compile_into(&b, symbol, pattern, flags, err, errsz);
  if (rc == 0 && !buf_write(&b, out_path)) {
    snprintf(err, errsz, "failed to open output file: %s", out_path);
    rc = 1;
  }
  free(b.data);
  return rc;
}

/* ------------------------------------------------------------
   Server mode

   One process serves a whole build instead of one process per regex literal:
   a project with a few hundred regexes was paying a process spawn -- tens of
   milliseconds on Windows -- for every one of them.

   Protocol, matching the native parser's framing:

     request   REGEX <pathLen> <symbolLen> <patternLen> <flagsLen>\n
               followed by exactly that many bytes of each field, in order,
               with nothing between them. Patterns may contain any byte,
               newlines and spaces included, so no field may be found by
               scanning for a delimiter.
     batch     REGEXB <pathLen> <count>\n
               <path bytes>, then <count> records, each being
                 <symbolLen> <patternLen> <flagsLen>\n
                 followed by those three fields back to back.
               All <count> regexes land in one file. This is the path that
               matters: writing the file costs ~2.5ms and compiling a regex
               ~0.01ms, so a module with 40 regexes goes from ~100ms to ~3ms.

     response  "OK 0\n"          on success
               "ERR <message>\n" on failure; the message is always one line

     "__quit__\n" shuts the server down.
   ------------------------------------------------------------ */

/* Reads one line and stops at the newline, leaving everything after it in the
   stream -- the payload follows the header immediately. Returns 0 at EOF. */
static int read_line(char* buf, size_t cap)
{
  size_t n = 0;
  int c;
  while ((c = fgetc(stdin)) != EOF) {
    if (c == '\n') {
      buf[n] = 0;
      return 1;
    }
    if (n + 1 < cap) {
      buf[n++] = (char)c;
    }
  }
  return 0;
}

static int read_exact(char* buf, size_t n)
{
  size_t got = 0;
  while (got < n) {
    size_t r = fread(buf + got, 1, n - got, stdin);
    if (r == 0) {
      return 0;
    }
    got += r;
  }
  buf[n] = 0;
  return 1;
}

static void respond_err(const char* msg)
{
  /* The framing is line-based, so a message must never contain a newline. */
  fputs("ERR ", stdout);
  for (const char* m = msg; *m; ++m) {
    fputc((*m == '\n' || *m == '\r') ? ' ' : *m, stdout);
  }
  fputc('\n', stdout);
  fflush(stdout);
}

static int run_server(void)
{
#ifdef _WIN32
  /* Without this the CRT rewrites \n as \r\n on these handles and every byte
     count in the protocol above becomes a lie. */
  _setmode(_fileno(stdin), _O_BINARY);
  _setmode(_fileno(stdout), _O_BINARY);
#endif

  char header[512];

  while (read_line(header, sizeof(header))) {
    if (strcmp(header, "__quit__") == 0) {
      return 0;
    }

    size_t batch_path_len = 0, batch_count = 0;
    if (sscanf(header, "REGEXB %zu %zu", &batch_path_len, &batch_count) == 2) {
      char* path = (char*)malloc(batch_path_len + 1);
      if (!path || !read_exact(path, batch_path_len)) {
        free(path);
        return 1;
      }

      outbuf b = { NULL, 0, 0 };
      buf_header(&b);
      char err[512];
      err[0] = 0;
      int failed = 0;

      for (size_t i = 0; i < batch_count; ++i) {
        char sub[256];
        size_t s_len = 0, p_len = 0, f_len = 0;
        if (!read_line(sub, sizeof(sub)) || sscanf(sub, "%zu %zu %zu", &s_len, &p_len, &f_len) != 3) {
          free(b.data);
          free(path);
          return 1;
        }

        char* sym = (char*)malloc(s_len + 1);
        char* pat = (char*)malloc(p_len + 1);
        char* flg = (char*)malloc(f_len + 1);
        if (!sym || !pat || !flg || !read_exact(sym, s_len) || !read_exact(pat, p_len)
            || !read_exact(flg, f_len)) {
          free(sym); free(pat); free(flg); free(b.data); free(path);
          return 1;
        }

        /* Keep draining the request even after a failure: the rest of it is
           still in the pipe and would otherwise be read as a new header. */
        if (!failed && compile_into(&b, sym, pat, flg, err, sizeof(err)) != 0) {
          failed = 1;
        }
        free(sym); free(pat); free(flg);
      }

      if (failed) {
        respond_err(err);
      } else if (!buf_write(&b, path)) {
        snprintf(err, sizeof(err), "failed to open output file: %s", path);
        respond_err(err);
      } else {
        fputs("OK 0\n", stdout);
        fflush(stdout);
      }

      free(b.data);
      free(path);
      continue;
    }

    size_t path_len = 0, sym_len = 0, pat_len = 0, flag_len = 0;
    if (sscanf(header, "REGEX %zu %zu %zu %zu", &path_len, &sym_len, &pat_len, &flag_len) != 4) {
      respond_err("bad request header");
      continue;
    }

    char* path = (char*)malloc(path_len + 1);
    char* symbol = (char*)malloc(sym_len + 1);
    char* pattern = (char*)malloc(pat_len + 1);
    char* flags = (char*)malloc(flag_len + 1);

    if (!path || !symbol || !pattern || !flags) {
      free(path);
      free(symbol);
      free(pattern);
      free(flags);
      respond_err("out of memory");
      return 1;
    }

    if (!read_exact(path, path_len) || !read_exact(symbol, sym_len) || !read_exact(pattern, pat_len)
        || !read_exact(flags, flag_len)) {
      /* The stream is truncated; there is nothing sensible left to read. */
      free(path);
      free(symbol);
      free(pattern);
      free(flags);
      return 1;
    }

    char err[512];
    err[0] = 0;
    if (compile_one(path, symbol, pattern, flags, err, sizeof(err)) == 0) {
      fputs("OK 0\n", stdout);
      fflush(stdout);
    } else {
      respond_err(err);
    }

    free(path);
    free(symbol);
    free(pattern);
    free(flags);
  }

  return 0;
}

/* ------------------------------------------------------------
   Main
   ------------------------------------------------------------ */

int main(int argc, char** argv)
{
  if (argc == 2 && strcmp(argv[1], "--server") == 0) {
    return run_server();
  }

  if (argc != 5) {
    printf("usage:\n"
           "  %s <output_c_path> <symbol_name> <pattern> <flags>\n"
           "  %s --server\n",
           argv[0],
           argv[0]);
    return 2;
  }

  char err[512];
  err[0] = 0;
  if (compile_one(argv[1], argv[2], argv[3], argv[4], err, sizeof(err)) != 0) {
    /* IMPORTANT: the caller reads errors from stdout, not stderr. */
    printf("%s\n", err);
    return 1;
  }

  return 0;
}
