// perfect-freehand 1.2.2, ported to C.
//
// The original is Steve Ruiz's JavaScript library
// (https://github.com/steveruizok/perfect-freehand, the npm package
// perfect-freehand 1.2.2), which technicalsketcher.web draws its strokes with:
//
//   MIT License
//
//   Copyright (c) 2021 Stephen Ruiz Ltd
//
//   Permission is hereby granted, free of charge, to any person obtaining a
//   copy of this software and associated documentation files (the
//   "Software"), to deal in the Software without restriction, including
//   without limitation the rights to use, copy, modify, merge, publish,
//   distribute, sublicense, and/or sell copies of the Software, and to permit
//   persons to whom the Software is furnished to do so, subject to the
//   following conditions:
//
//   The above copyright notice and this permission notice shall be included
//   in all copies or substantial portions of the Software.
//
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
//   NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
//   DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
//   OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
//   USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// The point of this port is to compute exactly what the library computes,
// down to the last bit, so a stroke looks the same here as in the web app and
// the outlines the web app stored in a file are the ones this recomputes. So
// it follows the JavaScript operation for operation, in the same order:
//
//   - lengths use Math.hypot's algorithm (scale by the larger, compensated
//     sum, sqrt), not sqrt(x*x + y*y), which rounds differently;
//   - the caps rotate by the angles the library's own loops produce, which
//     step by accumulating 1/13 or 1/29 and so are not i/13 -- the end cap
//     has 29 points, not 28 -- with the sines and cosines V8 computes for
//     them, tabulated below, since libm may round the odd one differently;
//   - no multiply-add is fused (see the pragma).
//
// Taper, flat caps and custom easings are not ported: nothing here passes
// them, and without them the library behaves as with its defaults.

#include <math.h>
#include <stdlib.h>
#include <string.h>

#include "public/perfect_freehand.h"

// A fused multiply-add rounds once where JavaScript rounds twice.
#if defined(__clang__)
#pragma clang fp contract(off)
#elif defined(__GNUC__)
#pragma GCC optimize("fp-contract=off")
#endif

typedef struct {
  double x;
  double y;
} hz_pf_vec_t;

typedef struct {
  hz_pf_vec_t point;
  double pressure;
  hz_pf_vec_t vector;
  double distance;
  double runningLength;
} hz_pf_stroke_point_t;

typedef struct {
  hz_pf_vec_t point;
  // The JavaScript point's third element: absent (undefined) for the points
  // the library interpolates itself.
  double pressure;
  int hasPressure;
} hz_pf_input_t;

typedef struct {
  hz_pf_vec_t* items;
  size_t count;
  size_t capacity;
} hz_pf_vec_list_t;

typedef struct hz_pf_context_t hz_pf_context_t;

// Everything pf_compute works in belongs to the context and is kept from one
// run to the next, so a context that computes stroke after stroke allocates
// only until it has seen the longest of them. A document has thousands of
// strokes: with the working arrays malloc'd and freed per run, they were some
// twenty allocations each.
struct hz_pf_context_t {
  hz_pf_input_t* points;
  size_t count;
  size_t capacity;

  double size;
  double thinning;
  double smoothing;
  double streamline;
  int simulatePressure;
  int last;

  hz_pf_stroke_point_t* strokePoints;
  size_t strokePointCapacity;
  hz_pf_vec_list_t leftPts;
  hz_pf_vec_list_t rightPts;

  hz_pf_vec_t* outline;
  size_t outlineCount;
  size_t outlineCapacity;

  // Of the outline, found on first request (see hz_pf_bounds).
  int hasBounds;
  hz_pf_vec_t boundsMin;
  hz_pf_vec_t boundsMax;
};

// Math.sin and Math.cos of the angles perfect-freehand rotates by, as V8
// computes them, in the order its loops produce them (generated by running
// those loops). V = Math.PI + 1e-4.
//   corner:    V * w and V * -w, w = 0, 1/13, 2/13, ... (accumulated) <= 1
//   dot:       V * 2 * u, u = 1/13, ... <= 1
//   startCap:  V * o, o = 1/13, ... <= 1
//   endCap:    V * 3 * u, u = 1/29, ... < 1
static const double hz_pf_corner_sin[14] = {
  0, 0.23932313306368833, 0.4647367943891659, 0.6631399313891804,
  0.8230013444193596, 0.9350298806433331, 0.9927144362721254, 0.9927023822222938,
  0.934994419075781, 0.8229445363620594, 0.6630650785290915, 0.46464824717803377,
  0.23922603786958413, -0.00009999999983253372,
};
static const double hz_pf_corner_cos[14] = {
  1, 0.9709399765076007, 0.8854488759611603, 0.74849544514122,
  0.5680394238817643, 0.3545689246170824, 0.12049086279430615, -0.12059013363531412,
  -0.3546624258321466, -0.5681217211758719, -0.7485617553917712, -0.8854953452132771,
  -0.9709639039661672, -0.999999995,
};
static const double hz_pf_cornerNeg_sin[14] = {
  -0.0, -0.23932313306368833, -0.4647367943891659, -0.6631399313891804,
  -0.8230013444193596, -0.9350298806433331, -0.9927144362721254, -0.9927023822222938,
  -0.934994419075781, -0.8229445363620594, -0.6630650785290915, -0.46464824717803377,
  -0.23922603786958413, 0.00009999999983253372,
};
static const double hz_pf_cornerNeg_cos[14] = {
  1, 0.9709399765076007, 0.8854488759611603, 0.74849544514122,
  0.5680394238817643, 0.3545689246170824, 0.12049086279430615, -0.12059013363531412,
  -0.3546624258321466, -0.5681217211758719, -0.7485617553917712, -0.8854953452132771,
  -0.9709639039661672, -0.999999995,
};
static const double hz_pf_dot_sin[13] = {
  0.4647367943891659, 0.8230013444193596, 0.9927144362721254, 0.934994419075781,
  0.6630650785290911, 0.23922603786958327, -0.2394202258645622, -0.6632147776178703,
  -0.9350653328605861, -0.9926903182454385, -0.8228877200753143, -0.46455969532041913,
  0.00019999999866506744,
};
static const double hz_pf_dot_cos[13] = {
  0.8854488759611603, 0.5680394238817643, 0.12049086279430615, -0.3546624258321466,
  -0.7485617553917715, -0.9709639039661674, -0.9709160393396341, -0.7484291274057142,
  -0.35447541985632985, 0.12068940327041966, 0.5682040127887616, 0.8855418056104406,
  0.9999999800000001,
};
static const double hz_pf_startCap_sin[13] = {
  0.23932313306368833, 0.4647367943891659, 0.6631399313891804, 0.8230013444193596,
  0.9350298806433331, 0.9927144362721254, 0.9927023822222938, 0.934994419075781,
  0.8229445363620594, 0.6630650785290915, 0.46464824717803377, 0.23922603786958413,
  -0.00009999999983253372,
};
static const double hz_pf_startCap_cos[13] = {
  0.9709399765076007, 0.8854488759611603, 0.74849544514122, 0.5680394238817643,
  0.3545689246170824, 0.12049086279430615, -0.12059013363531412, -0.3546624258321466,
  -0.5681217211758719, -0.7485617553917712, -0.8854953452132771, -0.9709639039661672,
  -0.999999995,
};
static const double hz_pf_endCap_sin[29] = {
  0.3193113334275621, 0.6051906859552526, 0.8277064139086023, 0.9635610618324479,
  0.9985306122270187, 0.928953743934938, 0.7621151734328964, 0.515482943093563,
  0.2148795125380521, -0.1082218597028758, -0.4199923746651157, -0.6877895771326984,
  -0.883575029315672, -0.9868499426881391, -0.9868014065580728, -0.8834345026711039,
  -0.68757177315041, -0.4197200974795481, -0.10792361680723146, 0.21517249503386945,
  0.5157399898449028, 0.7623093715770388, 0.929064760874929, 0.9985468244599354,
  0.9634807719332247, 0.8275380282508832, 0.6049518345618498, 0.3190270241024155,
  -0.0002999999954971571,
};
static const double hz_pf_endCap_cos[29] = {
  0.9476498680128185, 0.7960805446894245, 0.561161378192193, 0.26748846726602155,
  -0.05419055679300015, -0.37019581525087725, -0.6474414741297829, -0.8568998397593492,
  -0.9766405659665224, -0.9941267671089291, -0.9075276333110508, -0.7259101167414764,
  -0.46828961932740876, -0.16163907515330742, 0.16193512285791803, 0.4685546707591969,
  0.7261164209455679, 0.9076535901828179, 0.994159188930649, 0.9765760581649027,
  0.8567451563182482, 0.6472128104463168, 0.36991711247306625, 0.053890995175251456,
  -0.2677775235432533, -0.5614096648603768, -0.7962620660688617, -0.9477456187671652,
  -0.9999999550000004,
};

#define HZ_PF_RATE_OF_PRESSURE_CHANGE 0.275

// ── Vectors, as the library's vec.ts ─────────────────────────────────────

static inline hz_pf_vec_t hz_pf_add(hz_pf_vec_t a, hz_pf_vec_t b) { return (hz_pf_vec_t) { a.x + b.x, a.y + b.y }; }
static inline hz_pf_vec_t hz_pf_sub(hz_pf_vec_t a, hz_pf_vec_t b) { return (hz_pf_vec_t) { a.x - b.x, a.y - b.y }; }
static inline hz_pf_vec_t hz_pf_mul(hz_pf_vec_t a, double n) { return (hz_pf_vec_t) { a.x * n, a.y * n }; }
static inline hz_pf_vec_t hz_pf_div(hz_pf_vec_t a, double n) { return (hz_pf_vec_t) { a.x / n, a.y / n }; }
static inline hz_pf_vec_t hz_pf_per(hz_pf_vec_t a) { return (hz_pf_vec_t) { a.y, -a.x }; }
static inline hz_pf_vec_t hz_pf_neg(hz_pf_vec_t a) { return (hz_pf_vec_t) { -a.x, -a.y }; }
static inline double hz_pf_dpr(hz_pf_vec_t a, hz_pf_vec_t b) { return a.x * b.x + a.y * b.y; }
static inline int hz_pf_is_equal(hz_pf_vec_t a, hz_pf_vec_t b) { return a.x == b.x && a.y == b.y; }

// Math.hypot(a, b) as V8 implements it: normalized to the larger magnitude,
// summed with Kahan compensation, square-rooted and scaled back.
static double hz_pf_hypot(double a, double b)
{
  double absA = fabs(a);
  double absB = fabs(b);
  if (isnan(a) || isnan(b)) {
    return (isinf(a) || isinf(b)) ? INFINITY : NAN;
  }
  double max = 0.0;
  if (absA > max) {
    max = absA;
  }
  if (absB > max) {
    max = absB;
  }
  if (isinf(max)) {
    return INFINITY;
  }
  if (max == 0.0) {
    return 0.0;
  }
  double sum = 0.0;
  double compensation = 0.0;
  double n = absA / max;
  double summand = n * n - compensation;
  double preliminary = sum + summand;
  compensation = (preliminary - sum) - summand;
  sum = preliminary;
  n = absB / max;
  summand = n * n - compensation;
  preliminary = sum + summand;
  compensation = (preliminary - sum) - summand;
  sum = preliminary;
  return sqrt(sum) * max;
}

static inline double hz_pf_len(hz_pf_vec_t a) { return hz_pf_hypot(a.x, a.y); }
static inline double hz_pf_len2(hz_pf_vec_t a) { return a.x * a.x + a.y * a.y; }
static inline double hz_pf_dist2(hz_pf_vec_t a, hz_pf_vec_t b) { return hz_pf_len2(hz_pf_sub(a, b)); }
static inline hz_pf_vec_t hz_pf_uni(hz_pf_vec_t a) { return hz_pf_div(a, hz_pf_len(a)); }
static inline double hz_pf_dist(hz_pf_vec_t a, hz_pf_vec_t b) { return hz_pf_hypot(a.y - b.y, a.x - b.x); }
static inline hz_pf_vec_t hz_pf_lrp(hz_pf_vec_t a, hz_pf_vec_t b, double t) { return hz_pf_add(a, hz_pf_mul(hz_pf_sub(b, a), t)); }
static inline hz_pf_vec_t hz_pf_prj(hz_pf_vec_t a, hz_pf_vec_t b, double c) { return hz_pf_add(a, hz_pf_mul(b, c)); }

// rotAround, given the angle's sine and cosine.
static inline hz_pf_vec_t hz_pf_rot_around(hz_pf_vec_t a, hz_pf_vec_t c, double s, double co)
{
  double px = a.x - c.x;
  double py = a.y - c.y;
  double nx = px * co - py * s;
  double ny = px * s + py * co;
  return (hz_pf_vec_t) { nx + c.x, ny + c.y };
}

// Math.min / Math.max for the non-NaN values this sees.
static inline double hz_pf_min(double a, double b) { return b < a ? b : a; }
static inline double hz_pf_max(double a, double b) { return b > a ? b : a; }

// getStrokeRadius, with the default easing t => t.
static inline double hz_pf_radius(double size, double thinning, double pressure)
{
  return size * (0.5 - thinning * (0.5 - pressure));
}

// ── Growing arrays ───────────────────────────────────────────────────────

static void hz_pf_push(hz_pf_vec_list_t* list, hz_pf_vec_t v)
{
  if (list->count == list->capacity) {
    list->capacity = list->capacity < 64 ? 64 : list->capacity * 2;
    list->items = realloc(list->items, list->capacity * sizeof(hz_pf_vec_t));
  }
  list->items[list->count++] = v;
}

// ── getStrokePoints ──────────────────────────────────────────────────────

// The stroke points, in the context's own array: valid until the next run.
static hz_pf_stroke_point_t* hz_pf_get_stroke_points(hz_pf_context_t* ctx, size_t* outCount)
{
  *outCount = 0;
  if (ctx->count == 0) {
    return NULL;
  }
  double size = ctx->size;
  int isComplete = ctx->last;
  double t = 0.15 + (1.0 - ctx->streamline) * 0.85;

  // Two points become the first and four interpolated between it and the
  // second; one point gets a second one pixel off. Only those two cases
  // change the input, and both fit here.
  size_t n = ctx->count;
  hz_pf_input_t few[5];
  const hz_pf_input_t* pts = ctx->points;
  if (n <= 2) {
    memcpy(few, ctx->points, n * sizeof(hz_pf_input_t));
    pts = few;
  }
  if (n == 2) {
    hz_pf_vec_t last = few[1].point;
    for (int p = 1; p < 5; p++) {
      few[p].point = hz_pf_lrp(few[0].point, last, p / 4.0);
      few[p].hasPressure = 0;
      few[p].pressure = 0.0;
    }
    n = 5;
  }
  if (n == 1) {
    few[1].point = hz_pf_add(few[0].point, (hz_pf_vec_t) { 1.0, 1.0 });
    few[1].pressure = few[0].pressure;
    few[1].hasPressure = few[0].hasPressure;
    n = 2;
  }

  if (n > ctx->strokePointCapacity) {
    // Nothing of the last run is read again, so there is nothing to keep.
    free(ctx->strokePoints);
    ctx->strokePointCapacity = n < 64 ? 64 : n;
    ctx->strokePoints = malloc(ctx->strokePointCapacity * sizeof(hz_pf_stroke_point_t));
  }
  hz_pf_stroke_point_t* result = ctx->strokePoints;
  size_t count = 0;
  result[count++] = (hz_pf_stroke_point_t) {
    .point = pts[0].point,
    .pressure = pts[0].hasPressure && pts[0].pressure >= 0 ? pts[0].pressure : 0.25,
    .vector = { 1.0, 1.0 },
    .distance = 0.0,
    .runningLength = 0.0,
  };

  int hasReachedMinimumLength = 0;
  double runningLength = 0.0;
  hz_pf_stroke_point_t prev = result[0];
  size_t max = n - 1;
  for (size_t i = 1; i < n; i++) {
    hz_pf_vec_t point = isComplete && i == max ? pts[i].point : hz_pf_lrp(prev.point, pts[i].point, t);
    if (hz_pf_is_equal(prev.point, point)) {
      continue;
    }
    double distance = hz_pf_dist(point, prev.point);
    runningLength += distance;
    if (i < max && !hasReachedMinimumLength) {
      if (runningLength < size) {
        continue;
      }
      hasReachedMinimumLength = 1;
    }
    prev = (hz_pf_stroke_point_t) {
      .point = point,
      .pressure = pts[i].hasPressure && pts[i].pressure >= 0 ? pts[i].pressure : 0.5,
      .vector = hz_pf_uni(hz_pf_sub(prev.point, point)),
      .distance = distance,
      .runningLength = runningLength,
    };
    result[count++] = prev;
  }
  result[0].vector = count > 1 ? result[1].vector : (hz_pf_vec_t) { 0.0, 0.0 };

  *outCount = count;
  return result;
}

// ── getStrokeOutlinePoints ───────────────────────────────────────────────

// Makes room for an outline of `count` points, which is known before the
// first is written: one allocation, of exactly that, where growing by
// doubling took several and left up to half of the last unused.
static hz_pf_vec_t* hz_pf_outline_of(hz_pf_context_t* ctx, size_t count)
{
  if (count > ctx->outlineCapacity) {
    free(ctx->outline);
    ctx->outlineCapacity = count < 64 ? 64 : count;
    ctx->outline = malloc(ctx->outlineCapacity * sizeof(hz_pf_vec_t));
  }
  ctx->outlineCount = count;
  return ctx->outline;
}

static void hz_pf_get_stroke_outline_points(hz_pf_context_t* ctx, const hz_pf_stroke_point_t* points, size_t count)
{
  double size = ctx->size;
  double smoothing = ctx->smoothing;
  double thinning = ctx->thinning;
  int simulatePressure = ctx->simulatePressure;
  if (count == 0 || size <= 0) {
    return;
  }

  double totalLength = points[count - 1].runningLength;
  double minDistance = (size * smoothing) * (size * smoothing);

  hz_pf_vec_list_t* leftPts = &ctx->leftPts;
  hz_pf_vec_list_t* rightPts = &ctx->rightPts;
  leftPts->count = 0;
  rightPts->count = 0;

  // The average of the first ten pressures, so that lines do not start fat.
  double prevPressure = points[0].pressure;
  for (size_t i = 0; i < count && i < 10; i++) {
    double pressure = points[i].pressure;
    if (simulatePressure) {
      double sp = hz_pf_min(1.0, points[i].distance / size);
      double rp = hz_pf_min(1.0, 1.0 - sp);
      pressure = hz_pf_min(1.0, prevPressure + (rp - prevPressure) * (sp * HZ_PF_RATE_OF_PRESSURE_CHANGE));
    }
    prevPressure = (prevPressure + pressure) / 2.0;
  }

  double radius = hz_pf_radius(size, thinning, points[count - 1].pressure);
  double firstRadius = 0.0;
  int hasFirstRadius = 0;
  hz_pf_vec_t prevVector = points[0].vector;
  hz_pf_vec_t pl = points[0].point;
  hz_pf_vec_t pr = pl;
  hz_pf_vec_t tl = pl;
  hz_pf_vec_t tr = pr;
  int isPrevPointSharpCorner = 0;

  for (size_t i = 0; i < count; i++) {
    double pressure = points[i].pressure;
    hz_pf_vec_t point = points[i].point;
    hz_pf_vec_t vector = points[i].vector;
    double distance = points[i].distance;
    double runningLength = points[i].runningLength;

    // Noise at the end of the line.
    if (i < count - 1 && totalLength - runningLength < 3) {
      continue;
    }

    if (thinning != 0.0) {
      if (simulatePressure) {
        double sp = hz_pf_min(1.0, distance / size);
        double rp = hz_pf_min(1.0, 1.0 - sp);
        pressure = hz_pf_min(1.0, prevPressure + (rp - prevPressure) * (sp * HZ_PF_RATE_OF_PRESSURE_CHANGE));
      }
      radius = hz_pf_radius(size, thinning, pressure);
    }
    else {
      radius = size / 2.0;
    }
    if (!hasFirstRadius) {
      firstRadius = radius;
      hasFirstRadius = 1;
    }
    // No taper: the taper strengths are both 1.
    radius = hz_pf_max(0.01, radius * 1.0);

    hz_pf_vec_t nextVector = (i < count - 1 ? points[i + 1] : points[i]).vector;
    double nextDpr = i < count - 1 ? hz_pf_dpr(vector, nextVector) : 1.0;
    double prevDpr = hz_pf_dpr(vector, prevVector);
    int isPointSharpCorner = prevDpr < 0 && !isPrevPointSharpCorner;
    int isNextPointSharpCorner = nextDpr < 0;

    if (isPointSharpCorner || isNextPointSharpCorner) {
      // A rounded cap at the corner.
      hz_pf_vec_t offset = hz_pf_mul(hz_pf_per(prevVector), radius);
      for (size_t k = 0; k < sizeof(hz_pf_corner_sin) / sizeof(double); k++) {
        tl = hz_pf_rot_around(hz_pf_sub(point, offset), point, hz_pf_corner_sin[k], hz_pf_corner_cos[k]);
        hz_pf_push(leftPts, tl);
        tr = hz_pf_rot_around(hz_pf_add(point, offset), point, hz_pf_cornerNeg_sin[k], hz_pf_cornerNeg_cos[k]);
        hz_pf_push(rightPts, tr);
      }
      pl = tl;
      pr = tr;
      if (isNextPointSharpCorner) {
        isPrevPointSharpCorner = 1;
      }
      continue;
    }
    isPrevPointSharpCorner = 0;

    if (i == count - 1) {
      hz_pf_vec_t offset = hz_pf_mul(hz_pf_per(vector), radius);
      hz_pf_push(leftPts, hz_pf_sub(point, offset));
      hz_pf_push(rightPts, hz_pf_add(point, offset));
      continue;
    }

    hz_pf_vec_t offset = hz_pf_mul(hz_pf_per(hz_pf_lrp(nextVector, vector, nextDpr)), radius);
    tl = hz_pf_sub(point, offset);
    if (i <= 1 || hz_pf_dist2(pl, tl) > minDistance) {
      hz_pf_push(leftPts, tl);
      pl = tl;
    }
    tr = hz_pf_add(point, offset);
    if (i <= 1 || hz_pf_dist2(pr, tr) > minDistance) {
      hz_pf_push(rightPts, tr);
      pr = tr;
    }
    prevPressure = pressure;
    prevVector = vector;
  }

  hz_pf_vec_t firstPoint = points[0].point;
  hz_pf_vec_t lastPoint = count > 1 ? points[count - 1].point : hz_pf_add(points[0].point, (hz_pf_vec_t) { 1.0, 1.0 });

  if (count == 1) {
    // A dot.
    double dotRadius = hasFirstRadius && firstRadius != 0.0 ? firstRadius : radius;
    hz_pf_vec_t start = hz_pf_prj(firstPoint, hz_pf_uni(hz_pf_per(hz_pf_sub(firstPoint, lastPoint))), -dotRadius);
    size_t dotCount = sizeof(hz_pf_dot_sin) / sizeof(double);
    hz_pf_vec_t* out = hz_pf_outline_of(ctx, dotCount);
    for (size_t k = 0; k < dotCount; k++) {
      out[k] = hz_pf_rot_around(start, firstPoint, hz_pf_dot_sin[k], hz_pf_dot_cos[k]);
    }
    return;
  }

  // Left side, end cap, right side backwards, start cap.
  size_t startCapCount = sizeof(hz_pf_startCap_sin) / sizeof(double);
  size_t endCapCount = sizeof(hz_pf_endCap_sin) / sizeof(double);
  hz_pf_vec_t* out = hz_pf_outline_of(ctx, leftPts->count + endCapCount + rightPts->count + startCapCount);

  memcpy(out, leftPts->items, leftPts->count * sizeof(hz_pf_vec_t));
  out += leftPts->count;
  // The round end cap, a turn and a half.
  hz_pf_vec_t direction = hz_pf_per(hz_pf_neg(points[count - 1].vector));
  hz_pf_vec_t start = hz_pf_prj(lastPoint, direction, radius);
  for (size_t k = 0; k < endCapCount; k++) {
    *out++ = hz_pf_rot_around(start, lastPoint, hz_pf_endCap_sin[k], hz_pf_endCap_cos[k]);
  }
  for (size_t k = rightPts->count; k > 0; k--) {
    *out++ = rightPts->items[k - 1];
  }
  // The round start cap: the first right point rotated around the start.
  for (size_t k = 0; k < startCapCount; k++) {
    *out++ = hz_pf_rot_around(rightPts->items[0], firstPoint, hz_pf_startCap_sin[k], hz_pf_startCap_cos[k]);
  }
}

// ── The C API ────────────────────────────────────────────────────────────

hzstd_cptr_t pf_create(void)
{
  hz_pf_context_t* ctx = calloc(1, sizeof(hz_pf_context_t));
  // The library's defaults.
  ctx->size = 16.0;
  ctx->thinning = 0.5;
  ctx->smoothing = 0.5;
  ctx->streamline = 0.5;
  ctx->simulatePressure = 1;
  ctx->last = 0;
  return ctx;
}

void pf_destroy(hzstd_cptr_t handle)
{
  hz_pf_context_t* ctx = handle;
  if (!ctx) {
    return;
  }
  free(ctx->points);
  free(ctx->strokePoints);
  free(ctx->leftPts.items);
  free(ctx->rightPts.items);
  free(ctx->outline);
  free(ctx);
}

void pf_clear_points(hzstd_cptr_t handle)
{
  hz_pf_context_t* ctx = handle;
  ctx->count = 0;
  ctx->outlineCount = 0;
  ctx->hasBounds = 0;
}

void pf_add_point(hzstd_cptr_t handle, hzstd_f64_t x, hzstd_f64_t y, hzstd_f64_t pressure)
{
  hz_pf_context_t* ctx = handle;
  if (ctx->count == ctx->capacity) {
    ctx->capacity = ctx->capacity < 64 ? 64 : ctx->capacity * 2;
    ctx->points = realloc(ctx->points, ctx->capacity * sizeof(hz_pf_input_t));
  }
  // A point without pressure gets the library's default of 0.5 ({ x, y,
  // pressure = 0.5 }).
  ctx->points[ctx->count++] = (hz_pf_input_t) {
    .point = { x, y },
    .pressure = pressure >= 0 ? pressure : 0.5,
    .hasPressure = 1,
  };
}

void pf_set_size(hzstd_cptr_t handle, hzstd_f64_t size) { ((hz_pf_context_t*)handle)->size = size; }
void pf_set_thinning(hzstd_cptr_t handle, hzstd_f64_t thinning) { ((hz_pf_context_t*)handle)->thinning = thinning; }
void pf_set_smoothing(hzstd_cptr_t handle, hzstd_f64_t smoothing) { ((hz_pf_context_t*)handle)->smoothing = smoothing; }
void pf_set_streamline(hzstd_cptr_t handle, hzstd_f64_t streamline) { ((hz_pf_context_t*)handle)->streamline = streamline; }
void pf_set_simulate_pressure(hzstd_cptr_t handle, hzstd_i32_t value) { ((hz_pf_context_t*)handle)->simulatePressure = value != 0; }
void pf_set_last(hzstd_cptr_t handle, hzstd_i32_t value) { ((hz_pf_context_t*)handle)->last = value != 0; }

hzstd_i32_t pf_compute(hzstd_cptr_t handle)
{
  hz_pf_context_t* ctx = handle;
  ctx->outlineCount = 0;
  ctx->hasBounds = 0;
  if (ctx->count == 0) {
    return -1;
  }
  size_t count = 0;
  hz_pf_stroke_point_t* points = hz_pf_get_stroke_points(ctx, &count);
  hz_pf_get_stroke_outline_points(ctx, points, count);
  return 0;
}

hzstd_i32_t pf_get_outline_count(hzstd_cptr_t handle) { return (hzstd_i32_t)((hz_pf_context_t*)handle)->outlineCount; }

hzstd_f64_t pf_get_outline_x(hzstd_cptr_t handle, hzstd_i32_t index) { return ((hz_pf_context_t*)handle)->outline[index].x; }

hzstd_f64_t pf_get_outline_y(hzstd_cptr_t handle, hzstd_i32_t index) { return ((hz_pf_context_t*)handle)->outline[index].y; }

void pf_copy_outline(hzstd_cptr_t handle, hzstd_vec2_t* out, hzstd_f64_t divisor)
{
  hz_pf_context_t* ctx = handle;
  for (size_t i = 0; i < ctx->outlineCount; i++) {
    out[i].x = ctx->outline[i].x / divisor;
    out[i].y = ctx->outline[i].y / divisor;
  }
}

// The outline's bounds, found once per run and only when asked for.
static void hz_pf_bounds(hz_pf_context_t* ctx)
{
  if (ctx->hasBounds) {
    return;
  }
  ctx->hasBounds = 1;
  if (ctx->outlineCount == 0) {
    ctx->boundsMin = (hz_pf_vec_t) { 0.0, 0.0 };
    ctx->boundsMax = (hz_pf_vec_t) { 0.0, 0.0 };
    return;
  }
  hz_pf_vec_t min = ctx->outline[0];
  hz_pf_vec_t max = ctx->outline[0];
  for (size_t i = 1; i < ctx->outlineCount; i++) {
    hz_pf_vec_t p = ctx->outline[i];
    min.x = hz_pf_min(min.x, p.x);
    min.y = hz_pf_min(min.y, p.y);
    max.x = hz_pf_max(max.x, p.x);
    max.y = hz_pf_max(max.y, p.y);
  }
  ctx->boundsMin = min;
  ctx->boundsMax = max;
}

hzstd_f64_t pf_get_outline_min_x(hzstd_cptr_t handle)
{
  hz_pf_bounds(handle);
  return ((hz_pf_context_t*)handle)->boundsMin.x;
}

hzstd_f64_t pf_get_outline_min_y(hzstd_cptr_t handle)
{
  hz_pf_bounds(handle);
  return ((hz_pf_context_t*)handle)->boundsMin.y;
}

hzstd_f64_t pf_get_outline_max_x(hzstd_cptr_t handle)
{
  hz_pf_bounds(handle);
  return ((hz_pf_context_t*)handle)->boundsMax.x;
}

hzstd_f64_t pf_get_outline_max_y(hzstd_cptr_t handle)
{
  hz_pf_bounds(handle);
  return ((hz_pf_context_t*)handle)->boundsMax.y;
}
