name = "vimtest"
id = "vImTst01"
version = "0.1.0"
description = "vim differential test harness"
license = "MIT"
authors = []
src = "src"
type = "exe"

[dependencies]
textedit_behavior = { path = "../stdlib/textedit_behavior" }
text_document = { path = "../stdlib/text_document" }
vim_behavior = { path = "../stdlib/vim_behavior" }
