name = "gl"
version = "1.0.0"
description = "OpenGL support for Haze"
license = "MIT"
authors = ["HerrNamenlos123"]
type = "lib"
# src = "."

[linker]
# flags = ["-lm", "-lGL"]

[linker.linux]
flags = ["-lm", "-lGL"]
