// Auto-generated once by scripts/build-error-enum.ts from the numeric codes that
// were already at each throw site, then hand-maintained from here on: add new
// members by hand when adding new diagnostics, following the same ranges. Do not
// renumber an existing member — the value is the stable, load-bearing part.
//
// Mirrored on the Haze side in testsuite/src/error_codes.hz (same names, same
// values) so the test suite can assert on named codes instead of magic numbers.
// Keep both files in sync by hand when adding entries.
export enum HazeErrorCode {
  SyntaxError = 1000, // generic parser syntax error (from the ANTLR error listener)
  UnitNotKnownCompiler = 1001, // The unit '' is not known to the compiler
  UnitNotKnownCompiler2 = 1002, // The unit '' is not known to the compiler
  UnknownRegexFlag = 1003, // unknown regex flag ''
  DuplicateRegexFlag = 1004, // duplicate regex flag ''
  InvalidEscapeTrailing = 1005, // Invalid escape: trailing \
  InvalidXEscape = 1006, // Invalid \x escape
  InvalidUEscape = 1007, // Invalid \u escape
  InvalidUEscape2 = 1008, // Invalid \U escape
  UnknownEscape = 1009, // Unknown escape: \
  InvalidXEscape2 = 1010, // Invalid \x escape:
  InvalidUEscape3 = 1011, // Invalid \u escape:
  InvalidUEscape4 = 1012, // Invalid \U escape:
  MissingSourceLocationFilename = 1013, // Missing source location filename
  InvalidSourceLocationFormatExpectedPathFileHz = 1014, // Invalid source location format: expected "/path/to/file.hz:line:col[-endcol]", got ""
  SymbolWasAlreadyDeclaredThisScopePreviousDefinition = 2001, // Symbol '' was already declared in this scope. Previous definition:
  SymbolHasAlreadyBeenDeclaredAsStructWhich = 2002, // Symbol '' has already been declared as a Struct, which cannot be extended by a namespace. …
  SymbolHasAlreadyBeenDeclaredAsNamespaceWhich = 2003, // Symbol '' has already been declared as a Namespace, which cannot be extended by a struct. …
  StructAlreadyDeclaredThisScopeOriginalDefinition = 2004, // Struct '' is already declared in this scope. Original definition:
  FunctionThatNotMethodCannotBeMarkedAs = 2005, // A function that is not a method cannot be marked as 'static'
  ReservedNameItCannotBeUsedUserland = 2006, // '' is a reserved name, it cannot be used in userland.
  CannotFindImportNoSuchModule = 2007, // Cannot find import '': No such module
  IfLetBindingsElseIfBranchesAreNot = 2008, // 'if let' bindings in else-if branches are not supported yet
  LambdaFunctionNotAllowedHaveUncheckedCStyle = 2009, // A Lambda Function is not allowed to have unchecked, C-style variadic arguments
  LambdaFunctionsCannotHaveParameterPacks = 2010, // Lambda functions cannot have parameter packs
  FunctionDatatypesCannotHaveParameterPacks = 2011, // Function datatypes cannot have parameter packs
  FunctionDatatypesCannotDefineDefaultParameterValues = 2012, // Function datatypes cannot define default parameter values
  FunctionDatatypesCannotHaveParameterPacks2 = 2013, // Function datatypes cannot have parameter packs
  FunctionDatatypesCannotDefineDefaultParameterValues2 = 2014, // Function datatypes cannot define default parameter values
  NodiscardCanOnlyBeAppliedTaggedUnions = 2015, // nodiscard can only be applied to tagged unions
  ThisExpressionNotSuitableAsGenericTypeArgument = 3001, // This expression is not suitable as a generic type argument or literal value
  SymbolWasNotDeclaredThisScope = 3002, // Symbol '' was not declared in this scope
  MainFunctionDefinedButNotAllowedBecauseModule = 3003, // main function is defined, but not allowed because module is built as library
  NoMainFunctionDefinedGlobalScope = 3004, // No main function is defined in global scope
  MainFunctionMustReturnInt = 3005, // Main function must return int
  NoSuitableConversionFound = 4001, // No suitable conversion from type A to type B is known
  DefaultValueTypeRequestedButThisStructHas = 4002, // Default value for type '' is requested, but this struct has no default value because not a…
  DefaultValueTypeRequestedButNoSafeDefault = 4003, // Default value for type '' is requested, but no safe default value is known for that type
  NoSafeComparisonAvailableBetweenTypesAnd = 4004, // No safe comparison is available between types '' and ''
  NoSafeComparisonAvailableBetweenTypesAnd2 = 4005, // No safe comparison is available between types '' and ''
  NoSafeOperationKnownBetweenTypesAnd = 4006, // No safe operation is known between types '' and ''
  NoUnaryOperationKnownType = 4007, // No unary operation is known for type ''
  CtfeEvaluationFailed = 5001, // Compile-time evaluation (CTFE) of an expression failed
  CtfeNumericEvaluationFailed = 5002, // Compile-time evaluation of an expression as a numeric value failed
  ThisValueCannotBeEvaluatedAsInteger = 5003, // This value cannot be evaluated as an integer
  CtfeBooleanEvaluationFailed = 5004, // Compile-time evaluation of an expression as a boolean failed
  ValueCannotBeTestedTruthinessUseExplicitComparisons = 5005, // A value cannot be tested for truthiness, use explicit comparisons.
  ValueCannotBeTestedTruthinessUseExplicitComparisons2 = 5006, // A value cannot be tested for truthiness, use explicit comparisons.
  TypeExpressionCannotBeEvaluatedAsBooleanValue = 5007, // Type expression cannot be evaluated as a boolean value
  ExpressionCannotBeEvaluatedAsBooleanValueCompile = 5008, // Expression cannot be evaluated as a boolean value at compile time
  CannotConvertComplexCTValueExpressionYet = 5009, // Cannot convert complex CTValue to expression yet
  ThisExpressionNotValidLHS = 6001, // This expression is not a valid LHS
  ThisExpressionNotValidLHS2 = 6002, // This expression is not a valid LHS
  ThisExpressionNotValidLHS3 = 6003, // This expression is not a valid LHS
  CannotAssignTemporaryType = 6004, // Cannot assign to a temporary of type
  IntrinsicFunctionsLikeBuiltinEmbedFileCanOnly = 7001, // Intrinsic functions (like builtin.embed_file) can only be called directly, not
  BitwiseOrOperationBetweenAndNotAllowedSince = 7002, // Bitwise Or operation between '' and '' is not allowed since the enums are unrelated
  BitwiseOrOperationNotAllowedSinceItNot = 7003, // Bitwise Or operation on '' is not allowed since it is not a bitflag enum
  BitwiseOrOperationOnlyAllowedBitflagEnums = 7004, // Bitwise Or operation is only allowed on bitflag enums
  CannotCompareUnionsIncompatibleTypesAnd = 7005, // Cannot compare unions of incompatible types '' and ''
  FunctionCannotTakeAnyTypeParameters = 7006, // The function cannot take any type parameters
  FunctionMustTakeBetweenAndParameters = 7007, // The function must take between and parameters
  FunctionMustTakeExactlyParameterS = 7008, // The function must take exactly parameter(s)
  WithOperatorRequiresRightExpressionBeTypeAllocator = 7009, // The 'with' operator requires the right expression to be of type 'Allocator' (aka 'inline h…
  TakesExactly1ArgumentGot = 7010, // () takes exactly 1 argument, got
  ArgumentMustBeStringLiteralOrStringLiteral = 7011, // () argument must be a string literal or a string literal type (LiteralDatatype)
  EmbeddedFileSizeMBExceeds100MBLimit = 7012, // Embedded file size ( MB) exceeds 100 MB limit:
  FailedReadEmbeddedFile = 7013, // Failed to read embedded file:
  StaticAssertFunctionRequiresSecondParameterBeCompile = 7014, // The static_assert function requires the second parameter to be a compile-time-evaluable st…
  StaticAssertFailedWithMessage = 7015, // static_assert failed, with the user-supplied message
  StaticAssertEvaluatedFalse = 7016, // static_assert evaluated to false
  StaticPrintFunctionRequiresSecondParameterBeCompile = 7017, // The static_print function requires the second parameter to be a compile-time-evaluable str…
  PrimitiveConstructorsCannotTakeAnyTypeParameters = 7018, // Primitive constructors cannot take any type parameters
  StrConstructorMustTakeOneOrTwoParameters = 7019, // 'str' constructor must take one or two parameters
  PrimitiveConstructorDoesNotProvideOverloadThatCan = 7020, // Primitive constructor does not provide an overload that can take following types: ()
  PrimitiveNotConstructible = 7021, // Primitive is not constructible
  FunctionCallsAreNotAllowedHereStructMember = 7022, // Function calls are not allowed here. Struct member default values, global constant initial…
  FunctionNotFullyElaboratedYetIfItPart = 7023, // Function is not fully elaborated yet. If it is part of a recursive call chain, it requires…
  ExpressionTypeNotCallable = 7024, // Expression of type is not callable
  ThisCallRequiresLeastArgumentsButWereGiven = 7025, // This call requires at least arguments but were given
  ThisCallRequiresArgumentsButWereGiven = 7026, // This call requires arguments but were given
  DefaultInitializerCannotTakeAnyGenerics = 7027, // 'default' initializer cannot take any generics
  StructCalledButItDoesNotProvideConstructor = 7028, // Struct is called, but it does not provide a constructor
  ValueOutRangeLiteralType = 7029, // Value is out of range for literal type
  ValueOutRangeLiteralType2 = 7030, // Value is out of range for literal type
  BPrefixedStringDefinesSingleByteASCIICharacter = 7031, // A b"..."-prefixed string defines a single-byte ASCII character and cannot encode a non-ASC…
  EnumValueDoesNotExist = 7032, // Enum value '' does not exist in ''
  EnumValuesCanOnlyBeTypeStringOr = 7033, // Enum values can only be of type string or integer, not ''
  ThisEnumCannotHaveValuesWithMixedDatatypes = 7034, // This enum cannot have values with mixed datatypes '' and ''
  ThisValueDoesNotResolveIntegerThatPower = 7035, // This value does not resolve to an integer that is a power of two/an integer with exactly o…
  MultipleFieldsWithValueNotAllowed = 7036, // Multiple fields with value not allowed
  MultipleFieldsWithValueNotAllowed2 = 7037, // Multiple fields with value not allowed
  BitflagEnumsAreRequiredHaveIntegerValues = 7038, // bitflag enums are required to have integer values
  ThisEnumCannotHaveValuesWithMixedDatatypes2 = 7039, // This enum cannot have values with mixed datatypes '' and ''
  MultipleFieldsWithValueNotAllowed3 = 7040, // Multiple fields with value "" not allowed
  EnumWithStringValuesRequiresAllValuesBe = 7041, // An enum with string values requires all values to be defined
  ExpressionTypeDoesNotAllowOptionalChainingAs = 7042, // Expression of type '' does not allow optional chaining, as it requires a union with a 'nul…
  ExpressionTypeDoesNotAllowOptionalChainingAs2 = 7043, // Expression of type '' does not allow optional chaining, as it requires a union with a 'nul…
  ExpressionTypeDoesNotAllowOptionalChainingAs3 = 7044, // Expression of type '' does not allow optional chaining, as it requires a union with a 'nul…
  FnIntrinsicObjectDoesNotHaveMemberNamed = 7045, // 'fn' intrinsic object does not have a member named ''
  BuiltinNamespaceDoesNotDefineAnyDeclarationsNamed = 7046, // builtin namespace does not define any declarations named ''
  CompileTimeMemberAccessRequiresMemberExpressionEvaluate = 7047, // Compile-time member access requires the member expression to evaluate to a string literal
  CompileTimeMemberAccessRequiresMemberExpressionEvaluate2 = 7048, // Compile-time member access requires the member expression to evaluate to string, got
  ComptimeVariablesMustBeDeclaredAsConstUse = 7049, // Comptime variables must be declared as 'const'. Use 'const comptime', not 'let comptime'.
  GlobalConstantByDefinitionImmutableAndAlwaysRequired = 7050, // A global constant is by definition immutable and is always required to be initialized with…
  ThisExpressionNotEvaluableCompileTime = 7051, // This expression is not evaluable at compile time
  ThisIntrinsicCanOnlyTakeCompileTimeEvaluable = 7052, // This intrinsic can only take compile-time-evaluable string literals
  TypeExpectsTypeParametersButGot = 7053, // Type expects type parameters but got
  DefaultInitializerCannotTakeAnyGenerics2 = 7054, // 'default' initializer cannot take any generics
  FunctionUsesParameterPackButThereNotEnough = 7055, // Function uses a Parameter Pack, but there is not enough context around the function access…
  FunctionRequiresLeastParametersButAreGiven = 7056, // Function requires at least parameters, but are given
  FunctionOverloadedButNotDirectlyCalledSoThere = 7057, // Function '' is overloaded but not directly called, so there is not enough context to disam…
  AmbiguousOverloadCandidates = 7058, // No single overload candidate could be chosen unambiguously
  AmbiguousOverloadNeedsTypeAnnotation = 7059, // Ambiguous overload; disambiguate with explicit type annotations
  AmbiguousOverloadNeedsStructInit = 7060, // Ambiguous overload; disambiguate with explicit struct initialization
  ConflictingDeductionsGenericParameterFunctionPleaseSpecifyIt = 7061, // Conflicting deductions for generic parameter '' of function ''. Please specify it explicit…
  FunctionExpectsTypeParametersButGot = 7062, // Function expects type parameters but got
  NonExternFunctionGenericOrUsesParameterPack = 7063, // Non-Extern function '' is generic or uses a parameter pack, but does not define a body. (G…
  CStyleVarargParameterPackMayOnlyBe = 7064, // A C-Style Vararg parameter pack may only be used on extern "C" functions
  ParameterPackMayOnlyAppearVeryEndParameter = 7065, // A Parameter Pack may only appear at the very end of the parameter list
  ParameterPackMayNotBeUsedExternFunction = 7066, // A Parameter Pack may not be used on an extern function
  NonDefaultParameterCannotFollowDefaultOrOptional = 7067, // Non-default parameter '' cannot follow a default or optional parameter
  DefaultInitializerCannotTakeAnyGenerics3 = 7068, // 'default' initializer cannot take any generics
  CannotFindTypeParameter = 7069, // Cannot find type for parameter ''
  ConditionAccessesSymbolWhichNotParameterFunctionNow = 7070, // The condition accesses a symbol ('') which is not a parameter of the function. For now, on…
  CurrentlyNoreturnIfConditionsAreOnlyAllowedAccess = 7071, // Currently, noreturn_if() conditions are only allowed to access bool parameters, other type…
  UnsupportedExpressionNoreturnIfConstruct = 7072, // Unsupported expression in noreturn_if() construct
  FunctionDoesNotHaveBodySoNothingCan = 7073, // Function '' does not have a body, so nothing can be inferred by the compiler. Therefore it…
  MultiplyDefinedMainFunctionPreviousDefinition = 7074, // Multiply defined main function: Previous definition at
  MultiplyDefinedMainFunction = 7075, // Multiply defined main function
  TypeExpectsTypeParametersButGot2 = 7076, // Type expects type parameters but got
  ExpressionDoesNotEvaluateDatatype = 7077, // Expression '' does not evaluate to a datatype
  BuiltinNamespaceCannotTakeGenericArguments = 7078, // 'builtin' Namespace cannot take generic arguments
  UnexpectedBinaryOperationDatatype = 7079, // Unexpected binary operation on a datatype
  OperatorAccessAmbiguous = 7080, // Operator access is ambiguous
  ExpressionTypeNotValidLHSNoMatchingAssignment = 7081, // Expression of type '' is not a valid LHS, no matching assignment operator overload exists
  CannotAssignTemporaryType2 = 7082, // Cannot assign to a temporary of type
  OperatorRequiresNumericLeftHandSideGot = 7083, // Operator '' requires a numeric left-hand side, got ''
  OperatorRequiresNumericRightHandSideGot = 7084, // Operator '' requires a numeric right-hand side, got ''
  CannotUseMutateIntegerWithFloatingPointValue = 7085, // Cannot use '' to mutate integer '' with a floating-point value '': approximate values cann…
  CannotUseBetweenDifferentFloatingPointRealmsAnd = 7086, // Cannot use '' between different floating-point realms '' and '': explicit precision realms…
  CanOnlyBeAppliedReactiveValuesWrappingNumeric = 7087, // '' can only be applied to reactive values wrapping numeric types, got ''
  PrefixCanOnlyBeAppliedNumericTypesGot = 7088, // Prefix '' can only be applied to numeric types, got ''
  PostfixCanOnlyBeAppliedNumericTypesGot = 7089, // Postfix '' can only be applied to numeric types, got ''
  ConflictingFunctionWithSameSignatureAlreadyDefined = 7090, // A conflicting function with the same signature is already defined.
  FunctionNotFullyElaboratedYetIfItPart2 = 7091, // Function () is not fully elaborated yet. If it is part of a recursive call chain, it requi…
  MemberDoesNotExpectAnyTypeArgumentsBut = 7092, // Member '' does not expect any type arguments, but are given
  MethodStaticButCalledThroughObject = 7093, // Method () is static but is called through an object
  MethodNotStaticButCalledThroughTypeDid = 7094, // Method () is not static but is called through the type — did you mean to add 'static'?
  MethodCanMutateObjectButNotCalledObject = 7095, // Method () can mutate the object but is not called on an object that is mutable. Is it call…
  MethodRequiresObjectItCalledBeConstFully = 7096, // Method () requires the object it is called on to be const (fully immutable).
  MemberDoesNotExpectAnyTypeArgumentsBut2 = 7097, // Member '' does not expect any type arguments, but are given
  TypeValuesCannotExistRuntimeUseComptimeOr = 7098, // Type values cannot exist at runtime; use 'for comptime' or a compile-time index to access …
  ParameterPackNotSubstitutedYetAndDoesNot = 7099, // Parameter Pack is not substituted yet and does not have enough context to know its length
  ParameterPackDoesNotHaveMemberNamed = 7100, // Parameter Pack does not have a member named ''
  EnumsCannotTakeGenericArguments = 7101, // Enums cannot take generic arguments
  EnumDoesNotHaveValueNamed = 7102, // Enum '' does not have a value named ''
  UnionsCannotTakeGenericArguments = 7103, // Unions cannot take generic arguments
  UnionDoesNotHaveTagNamed = 7104, // Union '' does not have a tag named ''
  NamespaceDoesNotDefineAnyDeclarationsNamed = 7105, // Namespace '' does not define any declarations named ''
  DatatypeDoesNotHaveMemberNamed = 7106, // Datatype '' does not have a member named ''
  DatatypeDoesNotHaveMemberNamed2 = 7107, // Datatype '' does not have a member named ''
  DatatypeDoesNotHaveMemberNamed3 = 7108, // Datatype '' does not have a member named ''
  DatatypeDoesNotHaveMemberNamed4 = 7109, // Datatype '' does not have a member named ''
  ExpressionTypeDoesNotHaveMemberCalled = 7110, // Expression of type '' does not have a member called
  ReactiveDynamicArrayDoesNotHaveMemberNamed = 7111, // Reactive dynamic array does not have a member named ''
  FunctionRequiresCompileTimeEvaluableStringArgument = 7112, // The function requires a compile-time-evaluable string argument
  FunctionRequiresExactlyOneTypeParameter = 7113, // The function requires exactly one type parameter
  TypeDoesNotHaveAttributeNamed = 7114, // Type does not have an attribute named ''
  AttributeTypeHasValueThatNotType = 7115, // Attribute '' on type has a value that is not of type ''
  ArrayLiteralRequiresAllElementsBePlainValues = 7116, // An array literal requires all elements to be plain values and not 'key: value'-pairs.
  ArrayDatatypeRequiresElementsButAreGiven = 7117, // Array datatype requires elements, but are given
  StructMarkedAsOpaqueAndThereforeNoStruct = 7118, // Struct '' is marked as 'opaque' and therefore no struct literals are allowed outside of it…
  StructLiteralRequiresAllElementsBeKeyValue = 7119, // A struct literal requires all elements to be 'key: value'-pairs. Direct symbols and spread…
  DoesNotHaveMemberNamed = 7120, // does not have a member named ''
  CannotAssignMemberTwice = 7121, // Cannot assign member twice
  MembersWereNotAssignedAndNoDefaultValue = 7122, // Members were not assigned and no default value is known
  ThisExpressionNotEvaluableCompileTime2 = 7123, // This expression is not evaluable at compile time
  ThisIntrinsicCanOnlyTakeCompileTimeEvaluable2 = 7124, // This intrinsic can only take compile-time-evaluable string literals
  ComptimeIfLetStatementsNotSupportedYet = 7125, // Comptime 'if let' statements not supported yet
  ComptimeIfLetStatementsNotSupportedYet2 = 7126, // Comptime 'if let' statements not supported yet
  TypeIfLetExpressionNotImplicitlyConvertibleBool = 7127, // The type of the 'if let' expression is not implicitly convertible to bool, therefore a gua…
  TypeWhileLetExpressionNotImplicitlyConvertibleBool = 7128, // The type of the 'while let' expression is not implicitly convertible to bool, therefore a …
  CannotReturnThisContextItSNotFunction = 7129, // Cannot return in this context, it's not in a function context
  UninitializedDirectiveRequires0TypeArguments = 7130, // The 'uninitialized' directive requires 0 type arguments
  UninitializedDirectiveMayOnlyAppearExplicitUnsafeBlock = 7131, // The 'uninitialized' directive may only appear in an explicit unsafe block
  ComptimeVariablesMustBeDeclaredAsConstUse2 = 7132, // Comptime variables must be declared as 'const'. Use 'const comptime', not 'let comptime'.
  DefaultInitializerCannotTakeAnyGenerics4 = 7133, // 'default' initializer cannot take any generics
  VariableInitializationsWithDefaultInitializerRequireExplicitData = 7134, // Variable initializations with a 'default' initializer require an explicit datatype to be s…
  VariableRequiresInitializationValue = 7135, // Variable '' requires an initialization value
  VariableCannotBeAssignedDatatype = 7136, // A variable cannot be assigned a datatype
  VariableCannotBeAssignedVoidValue = 7137, // A variable cannot be assigned a 'void' value
  VariableCannotBeAssignedValueType = 7138, // A variable cannot be assigned a value of type
  ThisExpressionNotEvaluableCompileTime3 = 7139, // This expression is not evaluable at compile time
  ThisExpressionProducesValueTypeWhichMustBe = 7140, // This expression produces a value of type '' which must be handled
  CtfeStatementEvaluationFailed = 7141, // Compile-time evaluation of a statement expression failed
  EachLoopOverSomethingOtherThanParameterPack = 7142, // For each loop over something other than a parameter pack is not implemented yet
  EachLoopOverSomethingOtherThanParameterPack2 = 7143, // For each loop over something other than a parameter pack is not implemented yet
  EachLoopRequiresArrayTypeButGot = 7144, // For-each loop requires an array type, but got ''
  RaiseStatementCanOnlyBeUsedConjunctionWith = 7145, // A 'raise' statement can only be used in conjunction with a attempt/else construct, no corr…
  ThisStructAnonymousAndMustBeTypeInferred = 7146, // This struct is anonymous and must be type-inferred, but there is not enough context to inf…
  TypeNotValidTypeAggregateLiteral = 7147, // Type '' is not a valid type for an aggregate literal
  BuiltinTRequiresExactlyGeneric = 7148, // builtin.<T> requires exactly generic
  BuiltinRequiresResolveDatatype = 7149, // builtin. requires to resolve to a datatype
  VariableAccessCannotHaveTypeParameterList = 7150, // A variable access cannot have a type parameter list
  SymbolCannotBeUsedBeforeItSDeclared = 7151, // Symbol '' cannot be used before it's declared
  SymbolCannotBeUsedAsValueCode = 7152, // Symbol cannot be used as a value: Code
  TypeNotGeneric = 7153, // Type is not generic
  ErrorPropagationOperatorCanOnlyBeUsedExpressions = 7154, // The '?!' error propagation operator can only be used on expressions with a tagged union ty…
  ErrorPropagationOperatorCanOnlyBeUsedTagged = 7155, // The '?!' error propagation operator can only be used on tagged union types that provide bo…
  ThisComparisonAlwaysFalseAsNotMemberUnion = 7156, // This comparison is always false, as '' is not a member of the union ''.
  MultidimensionalArraySubscriptingNotImplementedYet = 7157, // Multidimensional array subscripting is not implemented yet
  OnlyIntegersCanBeUsedIndexArrays = 7158, // Only integers can be used to index arrays
  OnlyIntegersCanBeUsedIndexArrays2 = 7159, // Only integers can be used to index arrays
  ExpressionTypeCannotBeSubscripted = 7160, // Expression of type cannot be subscripted
  StructDoesNotHaveFieldNamed = 7161, // Struct '' does not have a field named ''
  OnlyIntegersCanBeUsedIndexArrays3 = 7162, // Only integers can be used to index arrays
  ExpressionTypeCannotBeSubscripted2 = 7163, // Expression of type cannot be subscripted
  StringsCannotBeIndexedMultipleDimensions = 7164, // Strings cannot be indexed in multiple dimensions
  OperatorAccessAmbiguous2 = 7165, // Operator access is ambiguous
  NoExactOverloadedOperatorTypeIndexTypeAvailable = 7166, // No exact overloaded operator in type '' for index type '' is available
  ExpressionTypeCannotBeSubscripted3 = 7167, // Expression of type '' cannot be subscripted
  ThisExpressionNotSuitableAsGenericTypeArgument2 = 7168, // This expression is not suitable as a generic type argument or literal value
  CouldNotInferGenericParameterFunctionPleaseSpecify = 7169, // Could not infer generic parameter '' for function ''. Please specify it explicitly.
  ThisDistroPackageManagerNotSupportedYetPlease = 8001, // This Distro/Package Manager is not supported yet, please report
  DeadCodeDetectedAndStripped = 9001, // Dead code detected and stripped
  EmbeddedFileSizeMBExceeds50MB = 9002, // Embedded file size ( MB) exceeds 50 MB:
  ThisMutModifierWillBeOverruledByConst = 9003, // This 'mut' modifier will be overruled by the 'const' declaration and have no effect
}
