name = "renderer"
version = "0.0.1"
description = "Immediate-mode WGPU 2D renderer: Context/Canvas/Frame/Renderer primitives"
license = "MIT"
authors = []
type = "lib"

[dependencies]
fontstash = { path = "./fontstash" }
wgpu = { path = "./wgpu" }
